name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/didgeridoomh/astro.git
    mkdir build
    cd build
    cmake ..
    make
  displayName: Build
